### ISSUE TITLE
Develop field experiment

### ISSUE THREAD

**Issue by huntallcott** [huntallcott/Lotteries#27]
The goal of this issue is to continue to consider the field experiment that @dtaubinsky @bblockwood and I discussed last week. This continues #3.

We would have the same intervention (providing information on expected value) that we're developing in #24, but outcomes (lottery ticket purchases) would be measured by people's actual purchases, not an MPL.

Two implementation options:
1. Lottery stores in a state that has them. Station an RA there, collect receipts when people exit.
2. Recruitment from an online panel, and ask people to keep a diary (like a food diary or expenditure diary, but it's a lottery expenditure diary). For this one, we would not be able to randomize prices.

My proposal would be that after we get the MTurk survey to a place we like it, we try to hire some RAs to implement option 1 over the summer. We'd need to get those people hired in the next few weeks I think, as people will presumably finalize summer jobs.

**Comment by huntallcott** [comment]
@bblockwood @dtaubinsky per Ben's email from last week, this task is assigned to us. 

I think I now favor option 2 from my original post above. Here is some additional detail.

We design an app that people can put on their phones and scan their lottery receipts + input the bottom line number. (There is a paper that does lottery expenditure diaries, so there is precedent. An app would be even easier, plus we could possibly use it for additional interventions and/or reminders to keep the diary.) We recruit either using online ads, or ideally if possible, from the Amerispeak/TESS people we're also using. People install the app and use it for a month to get used to it and gather baseline data.
After a month, we deliver a the EV intervention. Then we continue to measure purchases.

We take steps to reduce demand effects, such as telling people that the intervention is not to pressure them and we still want them to scan everything. I think we benefit from having powerful intervention that's an upper bound on bias, because (per @dtaubinsky's intuition) you need a lot of bias for lotteries to be welfare reducing, given that they are free money for the state.

This gives us the quantity effect of bias. 
Three options for price elasticity:
1. Tell people we pay them a rebate on their total purchases, and vary the rebate. Here we're worried about people gaming us. One way to check this is to also have people record total winnings (presumably mostly the smaller prizes) in some verifiable way through the app. (e.g. for MM, make people tell us their numbers purchased, and then match their numbers to whatever the winner was, or at least say that we'll do this in a fraction of cases. For scratch-offs, make people scan their cards if they won.) If people are gaming us, they might report less winnings because it's actually their friends that are winning. This will be noisy due to skewness, so perhaps we run a median regression or a winsorized OLS.
2. Remember that we also have a way of getting price elasticity (under some curvature assumption) using the response of purchases to the MM and PB jackpot amount. So maybe we can use that.
3. We can also keep the TESS MPL solely for the purpose of estimating price elasticity, even if we don't use it for bias estimation.

Obviously none of these is perfect.

But I think we agreed that we like the idea of a *field* experiment to measure bias instead of a "lab" experiment where the measurement of the outcome is only through an MPL, so I think some sacrifice is worth it.

Thoughts? Let's get this thread going.

**Comment by bblockwood** [comment]
Thanks @huntallcott. The idea of an app is very cool, and has some novelty in its own right. I wonder if there's a way of accomplishing the same thing with less overhead by just having a protocol for people to text message with us. (E.g., we send them text queries, they answer/send photos of anything like Lotto receipts or purchased tickets, we send them cash via apple or Android pay, etc.)

Recruiting from TESS could be nice, if it doesn't violate their terms, since it's a representative sample and we can link to their other responses. However, while I'm into the field experiment, I'm not yet sure we would want this to displace the bias estimation on TESS. And if we retain the EV treatment there,  then obviously a share of the respondents would already be treated. 

On price elasticity -- again I think it's worth retaining the MPL price elasticity estimation from TESS, but it would be nice to also have an estimate from the field. So on balance  I'd favor subsidizing ticket purchases, even if we're a little worried about gaming. I don't think we can use estimates of the jackpot elasticity to infer anything about price elasticities, because in principle we want to allow those to be different (and also for the odds-based demand elasticity to be different).

**Comment by huntallcott** [comment]
@bblockwood spoke today via phone about this. We are worried about experiment (2) because of under-reporting of purchases, demand effects, and possible forgetting of the intervention, and because getting the price elasticity would be difficult. We like the TESS design and getting a bound on bias as WTP-AnticipatoryUtility. Plan is to see what we get with the MTurk pilot and go from there.

**Comment by dtaubinsky** [comment]
makes sense. I think we can get a lot of mileage from the the Mturk/Tess experiments and the observational data.

**Comment by huntallcott** [comment]
Closing this, as I don't think we're prioritizing any field experiment.
