### ISSUE TITLE
Power calculation for Wharton app

### ISSUE THREAD

**Issue by huntallcott** [huntallcott/Lotteries#36]
The goal of this issue is to do a power calc for the Wharton app. 
I think the easiest and most important thing is to focus on the precision with which we can identify the income - purchase relationship, right? 

Below are some calculations.

![image](https://user-images.githubusercontent.com/23505296/61414044-fe93e700-a8ba-11e9-97be-2b3127e311ce.png)

Let's do a conservative calculation that is easy based on these numbers.
Focusi on the un-winsorized expenditures.
Shoot for four income groups and power to detect (with 95% confidence) differences in expenditures that differ by more than say 25% of the mean. Right now the standard error is 10, and so the error bar is 20, or about 56% of the mean. 

If we quadruple the sample size to 800 per income group, then our standard error bars go down to 10, and we can detect differences that are about ~25% of the mean. 

That gets us to a total sample of 3200 people.

@bblockwood do you think some version of this is enough to start with?
cc @rajbhargava @dtaubinsky

**Comment by bblockwood** [comment]
@huntallcott thanks, this is helpful and intuitive, and I agree the income-expenditure relationship is most important. I anticipate a fleshed out version of this calculation is sufficient. I have created a google doc here to compile this proposal. If you or @rajbhargava are willing and able to flesh this out in Section 2 there before I complete the rest, great. Otherwise, I'll take a shot based on this nice setup and run it by you tomorrow before sending. Thanks!

**Comment by bblockwood** [comment]
I added this to the proposal and just submitted it, so no need for further action on this issue for now.

**Comment by huntallcott** [comment]
Thank you @bblockwood. Sorry for my delay -- have been at NBER IO/Digitization and more today ...
