### ISSUE TITLE
Deploying Qualtrics survey via MTurk

### ISSUE THREAD

**Issue by jackblun** [huntallcott/Lotteries#6]
The goal of this issue is to deploy the pilot survey via Qualtrics / MTurk

**Comment by jackblun** [comment]
@anjoung can you do a sense check of the survey [here](https://docs.google.com/document/d/1OmfSWIoZxSoeYIY-hoBJpO9W5XNRNmaD5q3y89fh6PE/edit). The only thing that is yet to be finalized is the IRB statement at the top. I'm checking again with colleagues at Stanford what they usually do for pilots and should get responses today. A couple of things that would be great to get feedback on:
1) How long did it take? (in case we need to shorten)
2) Are the probability choices communicated clearly?

If these are all okay, could you outline the main steps for getting this into qualtrics / mturk, start getting that set up and share with me? I understand you're the expert on the practicalities of this! The aim is to have the pilot out in the next couple of days. Happy to chat on Skype any time if anything unclear - my skype is jackblun (I'm on central European time until Friday)

**Comment by jackblun** [comment]
@anjoung on the IRB, I've cleared up that so long as results aren't presented in outputs, its fine to run a limited pilot study. I've modified the survey accordingly. Let me know when you've done the above so we can get rolling with the survey!

**Comment by anjoung** [comment]
@jackblun Just read through the survey! Should be super easy to put together. I responded to some of your comments, and was confused about one of the questions (made a comment). 

For the section titled "Expected value treatments", I think that the language about average payment for players or splitting payments to each player might be a little confusing. The current text might make people think about how much money each player takes home, which leads people to get medians and averages confused. That being said, since you provide feedback, I think that people who are math literate should get the picture after maybe getting the first two questions wrong.

I think that your time estimate of ten minutes is correct. I finished it pretty quickly but math is pretty hard for most people so I suspect that ten minutes should prevent people from angrily emailing us. I can set up timers on each question to see how long it takes people to complete them, that way for future pilots we can adjust to the observed average value (and maybe +standard dev to accommodate for the math illiterate).

Also, should I include a comment section at the end? If you are concerned about, whether MTurkers were thinking about medians or averages, maybe just directly asking them might alleviate the concerns (at least internally).

**Comment by anjoung** [comment]
@jackblun I'll get this up first thing tomorrow morning, but I did not get any info about the budget, payment, or number.

**Comment by jackblun** [comment]
Ok I’ll follow up, thanks.

**Comment by jackblun** [comment]
@anjoung in your experience, would $2.50 a survey cut it?

**Comment by anjoung** [comment]
@jackblun In the future, when reviewing the edits the Google Doc, could you reject all edits you don't want and then message on the GitHub that you are done reviewing and all the current edits should be accepted? In other words, just leave behind the track changes of things you want changed so I have a record of what needs to be changed.

It makes it a lot easier and faster for me when I am implementing edits (that way I have all the track changes to follow). Let me know if this is cumbersome for you! Right now, it's fine but as the survey gets longer it will take me a lot longer to implement changes if I have to read the entire survey from top-to-bottom.

**Comment by jackblun** [comment]
Sure, that sounds good - thanks for letting me know!

**Comment by jackblun** [comment]
Hey @anjoung, any word on the survey results?

**Comment by bblockwood** [comment]
The pilot ran successfully over the weekend. I have just placed the raw data (.tsv file) in *dropbox/Externals/Data/*.

I have created a new issue (#7) to track data cleaning and analysis requests.
